language: node_js

node_js:
  - "12"
  - "10"

cache: npm

before_script:
  - npm run lint
  - npm run prettier:check

script:
  - npm test

branches:
  only:
    - master
    - /^v\d+\.\d+.\d+(-\d+)?$/ # e.g. `v3.2.1` | `v3.2.1-0`

notifications:
  email:
    on_success: never
    on_failure: always
