name: Test

on:
  pull_request:
    branches: ["**"]
  push:
    branches: [master]
    tags: ["**"]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run prettier:check
      - run: npm run lint
      - run: git config user.name "Actions" && git config user.email "actions@github.com"
      - run: npm test
